services:
  - type: web
    name: gold-trader-server
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
